version: "3.2"
services:
  apache:
    build: './containers/apache'
    ports:
    - 80:80
    volumes:
    - ./containers/apache/vhosts.d:/usr/local/apache2/conf/vhosts.d
    - dlamp:/var/www/dlamp
  php72:
    build: './containers/php72'
    volumes:
    - dlamp:/var/www/dlamp

  php71:
    build: './containers/php71'
    volumes:
    - dlamp:/var/www/dlamp

  php70:
    build: './containers/php70'
    volumes:
    - dlamp:/var/www/dlamp

  php56:
    build: './containers/php56'
    volumes:
    - dlamp:/var/www/dlamp

  mysql:
    build: './containers/mysql57'
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  dbdata:
  dlamp:

