version: "3.2"
services:
    apache:
        build: './containers/apache' 
        ports:
            - 80:80
        volumes:
            - ./containers/apache/vhosts.d/:/usr/local/apache2/conf/vhosts.d/
            - ./public_html/:/var/www/html/
    php72:
        build: './containers/php72'
        volumes:
            - ./public_html/:/var/www/html/

    php71:
        build: './containers/php71'
        volumes:
            - ./public_html/:/var/www/html/

    php70:
        build: './containers/php70'
        volumes:
            - ./public_html/:/var/www/html/

